##
## EPITECH PROJECT, 2024
## Makefile
## File description:
## make executables
##

NAME = do_op

SRC = *.c

ERROR = -Werror -Wall -Wextra

all:	comp

comp:
		gcc *.c

clean:
		rm -f a.out

fclean:	clean

re:		fclean all
